# Generated by Django 2.2.17 on 2021-01-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_type_id', models.IntegerField(choices=[(0, 'General'), (1, 'Semi-Private'), (2, 'Private')], primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout', models.DateTimeField(default=None, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedmanagement.Bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedmanagement.Patient')),
            ],
        ),
    ]
