# Generated by Django 2.2.17 on 2021-01-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type_id',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Semi-Private'), (2, 'Private')]),
        ),
    ]
